<?php

class Payment {
    
    protected $id;  // DB autoincrement
    protected $created;   // DB autogenerated with now()
    protected $amount;  // Stored in the currency smallest amount (i.e. GBP in pence)
    protected $tip;  // Stored in the currency smallest amount (i.e. GBP in pence)
    protected $tableNum;
    protected $restaurantId;  // Foreign Key to Restaurant table
    protected $paymentRef;
    protected $cardType;  // Int enum
    
    public function __construct(array $data) {
        if(isset($data['id'])) {
            $this->id = $data['id'];
        }
        if(isset($data['created'])) {
            $this->created = $data['created'];
        }
        $this->amount = $data['amount'];
        if(!isset($data['tip'])) {
            $this->tip = 0;
        }
        $this->tableNum = $data['tableNum'];
        $this->restaurantId = $data['restaurantId'];
        $this->paymentRef = $data['paymentRef'];
        $this->cardType = $data['cardType'];
    }

    public function getId() {
        return $this->id;
    }

    public function getCreated() {
        return $this->created;
    }

    public function getAmount() {
        return $this->amount;
    }

    public function getTip() {
        return $this->tip;
    }

    public function getTableNum() {
        return $this->tableNum;
    }

    public function getRestaurantId() {
        return $this->restaurantId;
    }

    public function getPaymentRef() {
        return $this->paymentRef;
    }

    public function getCardType() {
        return $this->cardType;
    }
}
