<?php

// Depending on the architecture, this class might be split between DB and a cache for faster token access
class User {

    protected $id;  // DB autoincrement
    protected $created;   // DB autogenerated with now()
    protected $username;
    protected $password;  // Hashed password
    protected $token;
    
    public function __construct(array $data) {
        if(isset($data['id'])) {
            $this->id = $data['id'];
        }
        if(isset($data['created'])) {
            $this->created = $data['created'];
        }
        $this->username = $data['username'];
        $this->password = $data['password'];
        $this->token = $data['token'];
    }

    public function getId() {
        return $this->id;
    }

    public function getCreated() {
        return $this->created;
    }

    public function getUsername() {
        return $this->username;
    }

    public function getPassword() {
        return $this->description;
    }

    public function getToken() {
        return $this->token;
    }

}
